### ISSUE TITLE
Change master url

### ISSUE THREAD

**Issue by Zhe-Shen** [marius311/cosmohome#21]
How did you achieve running the server on `http://cosmologyathome.org/` instead of `http://cosmologyathome.org/cosmohome/`? I posted a similar issue at your repo https://github.com/marius311/boinc-server-docker/issues/64. I followed your change of `config.xml` & `cosmohome.httpd.conf` on my own boinc project. Honestly, I think following two changes are critical
```
<master_url>${url_base}/</master_url>
```
in `config.xml`.
```
<Directory />
        Options FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>
```
in `cosmohome.httpd.conf`.

But when I access the master url, it shows
```
Forbidden
You don't have permission to access / on this server.
Apache/2.4.25 (Debian) Server at ${some_ip} Port 80
```
Could you help me figure out the issue? Thanks!

**Comment by marius311** [comment]
To be honest its so long since I did this I have no memory, but I think you're right that `config.xml` and `cosmohome.httpd.conf` are the two things you need to replicate, and I can confirm that the version of these files that you see here is exactly what we have running in production so there's nothing else behind the scenes. There's a few extra things in `cosmohome.httpd.conf` besides what you mention there, I would double check if any of them are important. The only other thing I can think of to check the Linux file system permissions on the relevant folders, which is maybe suggested by that error message. The apache user needs to be able to read them. Good luck!

**Comment by Zhe-Shen** [comment]
Thanks for your reply. I replaced the two files with yours but still not work. Do you include other commands that will change file system permission during build process? I wonder if it has to do with `docker-compose-admin.yml` & `./apache/supervisor.cosmohome.conf` as my project do not include them. Any further notes will be helpful. Thanks!

**Comment by Zhe-Shen** [comment]
Finally figured out the issue. It's due to some typos in my `*.httpd.conf` file. Anyway, thanks for your help!
